name: x_wire
description: "A Simple Windows WireGuard VPN Client Developed with Flutter."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  

  hugeicons: 
  wireguard_flutter: 
  window_manager:
  cross_connectivity:
  vclibs:
  flutter_riverpod: 
  file_picker:
  hive:
  hive_flutter:
  toastification: 
  text_highlight_codespark: 
  tray_manager: 
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf